<?php

namespace App\Http\Requests\Customer;

use Illuminate\Foundation\Http\FormRequest;

class RegisterCustomerRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name'                   => 'required|string|min:3|max:20',
            'email'                  => 'required|string|unique:customers,email'.$this->id,
            'password'               => 'required|string|min:8|regex:/[0-9]/|regex:/[A-Z]/|regex:/[a-z]/|regex:/[@#$%^&*()_+!]/',
            'confirm_password'       => 'required|string|min:8|regex:/[0-9]/|regex:/[A-Z]/|regex:/[a-z]/|regex:/[@#$%^&*()_+!]/',
        ];
    }
    public function messages()
    {
       return [
           'password.regex'                => 'password you should be contain small,large letter , number ,@@#...',
//           'confirm_password.regex'        => 'confirm password you should be contain small,large letter , number ,@@#...'
       ];
        // return parent::messages(); // TODO: Change the autogenerated stub
    }
}
